apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-app-config
data:
  SERVICE_NAME: "sample-app"
  VERSION: "0.1.0"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "postgres"
  DB_SSLMODE: "disable"
