apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
- namespace.yaml
- ../../base/app
- ../../base/postgres
images:
- name: sample-app
  newName: ghcr.io/mhever/sample-app
  newTag: sha-6b89aac

replicas:
- name: sample-app
  count: 2