apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/app
- ../../base/postgres
images:
- name: sample-app
  newName: ghcr.io/mhever/sample-app
  newTag: main

replicas:
- name: sample-app
  count: 3